version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://tradingbot_user:password@db/tradingbot_db
      - JWT_SECRET_KEY=test_jwt_secret
      - SECRET_KEY=test_flask_secret
      - FLASK_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tradingbot_db
      - MYSQL_USER=tradingbot_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
